"""empty message

Revision ID: 4a59b1f2f370
Revises: a3f43f6de27e
Create Date: 2017-07-05 22:17:08.980122

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4a59b1f2f370'
down_revision = 'a3f43f6de27e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('product_categories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=True),
    sa.Column('description', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.add_column(u'products', sa.Column('product_category', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'products', 'product_picture_articles', ['product_category'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'products', type_='foreignkey')
    op.drop_column(u'products', 'product_category')
    op.drop_table('product_categories')
    # ### end Alembic commands ###
