"""empty message

Revision ID: c4e7e2365fd7
Revises: 4a59b1f2f370
Create Date: 2017-07-09 09:29:14.394665

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'c4e7e2365fd7'
down_revision = '4a59b1f2f370'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('news_articles', 'title')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('news_articles', sa.Column('title', mysql.VARCHAR(length=50), nullable=True))
    # ### end Alembic commands ###
